@echo off
rem SECRET_KEY is auto-generated by app.py if unset/weak. Set a strong value in production.
set DATABASE_URL=sqlite:///social_media.db
set FLASK_ENV=development
set REDIS_HOST=127.0.0.1
set REDIS_PORT=6379
cd /d C:\Users\User\Desktop\Svyaz.git
python app.py
